#XPath
//button[@class="btn btn-outline-white header_signin"]
//p[@text()="Log furl expenses"]
//button[contains(@class, "hero-descriptor*btn") and text()="Sign up"]
//div[@class="contacts_socials socials"]
//span[@class="socials_icon icon icon-facebook"]
//p[contains(text(), "manual testing")]
//div[contains(@class, "hero-descriptor")]
//section[@class="section hero"]
//label[@for='signupEmail']
//meta[@name='viewport']
//button[@class="btn btn-outline-white header_signin"]
//a[@class='socials_link']
//section[@class='section hero']
//a[@target="_blank" and @rel="nofollow"]
//footer[@class='footer d-flex align-items-center']
//button[@type='button' and @disabled]
//ngb-modal-window[@role='dialog' and @tabindex='-1']
//div[@class='modal-title']
//button[contains(@class, "header_signin")]
//p[text()="Log fuel expenses"]
//p[contains(@class, "about-block*title") and text()="Log fuel expenses"]
//ngb-modal-backdrop[contains(@class, "modal-backdrop")]
//span[@aria-hidden='true']
//ngb-modal-backdrop[@style='z-index: 1050;']
//div[contains(@class, "col-12 col-lg-4")]
//h1[text()="Do more!"]

#CSS
div.col-lg-4 
button[class='btn btn-outline-white header_signin']
h1.display-2
div.hero-descriptor 
p.lead
button.btn-primary
class="btn btn-outline-white header_signin"
h1[_ngcontent-fdv-c80] 
button[_ngcontent-fdv-c80]
app-user-nav[_nghost-fdv-c55]
header[class='header bg-basic-dark']
a[routerlink="/"]
svg[height="30"]
button[title="Play"]
a[target="_blank"]
img[alt="Instructions"]
p[class="about-block_descr lead"]
span[class="socials_icon icon icon-instagram"]
a[href="mailto:developer@ithillel.ua"]
p[class="about-block_title h2"]
img[class="about-picture_img"]
button[class="hero-descriptor_btn btn btn-primary"]
div[class="guest-layout"]
section[class="section hero"]
input[id="signinPassword"]